lib/gate_goat_web/router.ex
defmodule GateGoatWeb.Router do
  use GateGoatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug :fetch_session
    plug Guardian.Plug.Pipeline, module: GateGoat.Guardian,
                                 error_handler: GateGoat.AuthErrorHandler
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug GateGoat.CurrentUser
  end

  pipeline :admin do
    plug GateGoat.AdminUser
  end

  pipeline :event_manager do
    plug GateGoat.EventManagerUser
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :admin, :browser]

    resources "/fees", FeeController
    resources "/users", UserController, only: [:index, :delete, :show, :create, :new]
    resources "/roles", RoleController
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :event_manager, :browser]

    resources "/events", EventController do
      resources "/activities", ActivityController, only: [:create, :new, :edit]
    end

    resources "/register", RegistrationController, only: [:index, :delete]
    resources "/activities", ActivityController, only: [:index, :delete, :create, :new, :edit, :update]
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :browser]

    resources "/register", RegistrationController, only: [:edit, :update]
    resources "/users", UserController, only: [:edit, :update]

    get "/admin", AdminController, :index
    get "/lookup", LookupController, :lookup
    post "/lookup", LookupController, :lookup
  end

  scope "/", GateGoatWeb do
    pipe_through :browser # Use the default browser stack

    get "/", GateGoatController, :index
    get "/about", GateGoatController, :about
    get "/instructions", GateGoatController, :instructions
    get "/event/:id", GateGoatController, :register
    resources "/register", RegistrationController, only: [:show, :create, :new]
    resources "/activities", ActivityController, only: [:index, :show]

    resources "/events", EventController do
      resources "/activities", ActivityController, only: [:index]
    end

    get "/login", LoginController, :login
    post "/login", LoginController, :login
    post "/logout", LoginController, :logout
  end


  # Other scopes may use custom stacks.
  # scope "/api", GateGoatWeb do
  #   pipe_through :api
  # end
end

lib/gate_goat/activities/activities.ex
defmodule GateGoat.Activities do
  @moduledoc """
  The Activities context.
  """

  import Ecto.Query, warn: false
  alias GateGoat.Repo

  alias GateGoat.Activities.Activity

  @doc """
  Returns the list of activities.

  ## Examples

      iex> list_activities()
      [%Activity{}, ...]

  """
  def list_activities do
    Repo.all(from c in Activity, where: is_nil(c.replaced_by_id))
    |> Repo.preload(:event)
  end

  def list_activities_for_event(event_id) do
    Repo.all(from c in Activity, where: c.event_id == ^event_id and is_nil(c.replaced_by_id))
  end

  @doc """
  Gets a single activity.

  Raises `Ecto.NoResultsError` if the Activity does not exist.

  ## Examples

      iex> get_activity!(123)
      %Activity{}

      iex> get_activity!(456)
      ** (Ecto.NoResultsError)

  """
  def get_activity!(id) do
    Repo.get!(Activity, id)
    |> Repo.preload(:event)
  end

  def get_activity_by_replacement(id) do
    Repo.one(from c in Activity, where: c.replaced_by_id == ^id)
  end

  @doc """
  Creates a activity.

  ## Examples

      iex> create_activity(%{field: value})
      {:ok, %Activity{}}

      iex> create_activity(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_activity(attrs \\ %{}) do
    %Activity{}
    |> Activity.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a activity.

  ## Examples

      iex> update_activity(activity, %{field: new_value})
      {:ok, %Activity{}}

      iex> update_activity(activity, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_activity(%Activity{} = activity, attrs) do
    with {:ok, new_activity} <- create_activity(attrs),
         {:ok, activity} <- update_replaced_by_id(activity, new_activity)
    do
      {:ok, new_activity}
    else
      _ -> {:error, activity}
    end
  end

  def create_new_activity(attrs) do
    attrs
    |> Map.delete("event")
    |> create_activity()
    |> Repo.preload(:event)
  end

  def update_replaced_by_id(activity, new_activity) do
    activity
    |> Activity.changeset(%{replaced_by_id: new_activity.id})
    |> Repo.update()
  end

  @doc """
  Deletes a Activity.

  ## Examples

      iex> delete_activity(activity)
      {:ok, %Activity{}}

      iex> delete_activity(activity)
      {:error, %Ecto.Changeset{}}

  """
  def delete_activity(%Activity{} = activity) do
    historical_activity = get_activity_by_replacement(activity.id)
    unless historical_activity == nil do
      delete_activity(historical_activity)
    end

    Repo.delete(activity)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking activity changes.

  ## Examples

      iex> change_activity(activity)
      %Ecto.Changeset{source: %Activity{}}

  """
  def change_activity(%Activity{} = activity) do
    Activity.changeset(activity, %{})
  end

  def updated_activities(activities) do
    Enum.reduce(activities, [], fn(x, acc) ->
      item = Repo.all(from c in Activity, where: c.replaced_by_id == ^x.id)
      acc ++ item
    end)
  end
end

lib/gate_goat/activities/activity.ex
defmodule GateGoat.Activities.Activity do
  use Ecto.Schema
  import Ecto.Changeset

  schema "activities" do
    field :description, :string
    field :duration, :integer
    field :name, :string
    field :owner, :string
    field :start_time, :naive_datetime
    field :replaced_by_id, :integer
    belongs_to :event, GateGoat.Events.Event

    timestamps()
  end

  @doc false
  def changeset(activity, attrs) do
    activity
    |> cast(attrs, [:name, :start_time, :duration, :description, :owner, :event_id, :replaced_by_id])
    |> cast_assoc(:event, with: &GateGoat.Events.Event.changeset/2)
    |> validate_required([:name, :start_time, :duration, :description, :owner])
  end
end

lib/gate_goat_web/controllers/activity_controller.ex
defmodule GateGoatWeb.ActivityController do
  use GateGoatWeb, :controller

  alias GateGoat.Activities
  alias GateGoat.Activities.Activity

  def index(conn, %{"event_id" => event_id}) do
    activities = Activities.list_activities_for_event(event_id)

    conn
    |> render("index.html", activities: activities, event: GateGoat.Events.get_event!(event_id))
    end
  def index(conn, _params) do
    user = GateGoat.AdminHelper.current_user(conn)

    if user.role.type == "admin" do
      activities = Activities.list_activities()

      conn
      |> render("index_admin.html", activities: activities)
    else
      activities = Activities.list_activities_for_event(user.event.id)

      conn
      |> render("index.html", activities: activities, event: GateGoat.Events.get_event!(user.event.id))
    end
  end

  def new(conn, %{"event_id" => event_id}) do
    event = GateGoat.Events.get_event!(event_id)
    {:ok, date} = NaiveDateTime.new(event.event_date, ~T[00:00:00])

    changeset = Activities.change_activity(%Activity{event_id: event_id, start_time: date})
    render(conn, "new.html", changeset: changeset)
  end

  #this feels like cheating
  def create(conn, %{"action" => "filter", "event" => event_id}) do
    activities = Activities.list_activities_for_event(event_id)
                 |> GateGoat.Repo.preload(:event)

    conn
    |> render("index_admin.html", activities: activities)
  end
  def create(conn, %{"action" => "clear"}) do
    index(conn, nil)
  end
  def create(conn, %{"activity" => activity_params}) do
    case Activities.create_activity(activity_params) do
      {:ok, activity} ->
        conn
        |> put_flash(:info, "Activity created successfully.")
        |> redirect(to: Routes.activity_path(conn, :show, activity))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    activity = Activities.get_activity!(id)
    render(conn, "show.html", activity: activity)
  end

  def edit(conn, %{"id" => id}) do
    activity = Activities.get_activity!(id)
    changeset = Activities.change_activity(activity)
    render(conn, "edit.html", activity: activity, changeset: changeset)
  end

  def update(conn, %{"id" => id, "activity" => activity_params}) do
    activity = Activities.get_activity!(id)

    case Activities.update_activity(activity, activity_params) do
      {:ok, activity} ->
        conn
        |> put_flash(:info, "Activity updated successfully.")
        |> redirect(to: Routes.activity_path(conn, :show, activity))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", activity: activity, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    activity = Activities.get_activity!(id)
    {:ok, _activity} = Activities.delete_activity(activity)

    conn
    |> put_flash(:info, "Activity deleted successfully.")
    |> redirect(to: Routes.activity_path(conn, :index))
  end
end

lib/gate_goat_web/views/activity_view.ex
defmodule GateGoatWeb.ActivityView do
  use GateGoatWeb, :view

  def items_changed(activity) do
    new_activity = activity.replaced_by_id
    |> GateGoat.Activities.get_activity!()
    |> Map.from_struct()

    activity = activity
    |> Map.from_struct()
    |> Map.delete(:event)
    |> Map.delete(:replaced_by_id)
    |> Map.delete(:id)
    |> Map.delete(:inserted_at)
    |> Map.delete(:created_at)

    Enum.reduce(activity, [], fn({key, value}, acc) ->
      if value != new_activity[key] do
        proper_name = key
        |> Atom.to_string()
        |> String.replace("_", " ")
        |> String.capitalize()
        [%{name: proper_name, old_value: make_human_readable(value), new_value: make_human_readable(new_activity[key])} | acc]
      else
        acc
      end
    end)
  end

  def make_human_readable(%NaiveDateTime{} = datetime) do
    "#{datetime.month}/#{datetime.day} at #{format_time(datetime.hour, datetime.minute)}"
  end
  def make_human_readable(value), do: value

  defp format_minutes(minute) do
    if minute < 10 do
      "0#{minute}"
    else
      minute
    end
  end

  defp format_time(hour, minute) do
    if hour > 12 do
      "#{hour - 12}:#{format_minutes(minute)} PM"
    else
      "#{hour}:#{format_minutes(minute)} AM"
    end
  end
end

lib/gate_goat_web/templates/activity/edit.html.eex
<h1>Edit Activity</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.activity_path(@conn, :update, @activity)) %>

<span><%= link "Back", to: Routes.activity_path(@conn, :index) %></span>

lib/gate_goat_web/templates/activity/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :event_id %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :start_time %>
  <%= datetime_select f, :start_time, builder: fn b -> %>
        Date: <%= b.(:day, []) %> / <%= b.(:month, []) %> / <%= b.(:year, []) %>
        Time: <%= b.(:hour, []) %> : <%= b.(:minute, []) %>
      <% end %>
  <%= error_tag f, :start_time %>

  <%= label f, :duration %>
  <%= number_input f, :duration %>
  <%= error_tag f, :duration %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :owner %>
  <%= text_input f, :owner %>
  <%= error_tag f, :owner %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/gate_goat_web/templates/activity/index.html.eex
<%= if GateGoat.Activities.updated_activities(@activities) != [] do %>

  <h3>The following activities have been modified:</h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Time Updated</th>
        <th>Changes</th>
      </tr>
    </thead>

    <tbody>
    <%= for activity <- GateGoat.Activities.updated_activities(@activities) do %>
        <tr>
          <td><%= activity.name %></td>
          <td><%= make_human_readable(activity.inserted_at) %></td>
          <td>
            <ul>
              <%= for item <- items_changed(activity) do %>
                <li><%= "#{item.name}: #{item.old_value} -> #{item.new_value}" %></li>
              <% end %>
            </ul>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

<% end %>

<hr>
<h1>Schedule</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Owner</th>
      <%= if GateGoat.AdminHelper.admin?(@conn) || GateGoat.AdminHelper.event_manager?(@conn) do %>
       <th></th>
      <% end %>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for activity <- @activities do %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= make_human_readable(activity.start_time) %></td>
      <td><%= activity.duration %></td>
      <td><%= activity.description %></td>
      <td><%= activity.owner %></td>
      <%= if GateGoat.AdminHelper.admin?(@conn) || GateGoat.AdminHelper.event_manager?(@conn) do %>
        <td><%= link "Edit", to: Routes.event_activity_path(@conn, :edit, @event, activity) %></td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>

<%= if GateGoat.AdminHelper.admin?(@conn) || GateGoat.AdminHelper.event_manager?(@conn) do %>
  <span><%= link "New Activity", to: Routes.event_activity_path(@conn, :new, @event) %></span><br>
<% end %>

<span><%= link "Back", to: Routes.gate_goat_path(@conn, :index) %></span>

lib/gate_goat_web/templates/activity/index_admin.html.eex
<h1>Listing Activities</h1>

<%= form_for @conn, Routes.activity_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <label>
      Event: <%= select f, :event, Enum.map(GateGoat.Events.list_current_events(), &{&1.event_name, &1.id}) %>
    </label>
    <%= submit "Filter", class: "button", name: "action", value: "filter" %>
    <%= submit "Clear", class: "button", name: "action", value: "clear" %>
  </div>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Owner</th>

      <th></th>
    </tr>
  </thead>
  <tbody>

<%= for activity <- @activities do %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.event.event_name %></td>
      <td><%= activity.start_time %></td>
      <td><%= activity.duration %></td>
      <td><%= activity.description %></td>
      <td><%= activity.owner %></td>

      <td>
        <%= link "Show", to: Routes.activity_path(@conn, :show, activity) %>
        <%= link "Edit", to: Routes.activity_path(@conn, :edit, activity) %>
        <%= link "Delete", to: Routes.activity_path(@conn, :delete, activity), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= for event <- GateGoat.Events.list_current_events() do %>
  <span><%= link "New Activity for #{event.event_name}", to: Routes.event_activity_path(@conn, :new, event) %></span><br>
<% end %>

<span><%= link "Back", to: Routes.admin_path(@conn, :index) %></span>

lib/gate_goat_web/templates/activity/new.html.eex
<h1>New Activity</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.activity_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.activity_path(@conn, :index) %></span>

lib/gate_goat_web/templates/activity/show.html.eex
<h1>Show Activity</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @activity.name %>
  </li>

  <li>
    <strong>Start time:</strong>
    <%= @activity.start_time %>
  </li>

  <li>
    <strong>Duration:</strong>
    <%= @activity.duration %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @activity.description %>
  </li>

  <li>
    <strong>Owner:</strong>
    <%= @activity.owner %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.activity_path(@conn, :edit, @activity) %></span>
<span><%= link "Back", to: Routes.activity_path(@conn, :index) %></span>