lib/gate_goat_web/router.ex
defmodule GateGoatWeb.Router do
  use GateGoatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug :fetch_session
    plug Guardian.Plug.Pipeline, module: GateGoat.Guardian,
                                 error_handler: GateGoat.AuthErrorHandler
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug GateGoat.CurrentUser
  end

  pipeline :admin do
    plug GateGoat.AdminUser
  end

  pipeline :event_manager do
    plug GateGoat.EventManagerUser
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :admin, :browser]

    resources "/fees", FeeController
    resources "/users", UserController, only: [:index, :delete, :show, :create, :new]
    resources "/roles", RoleController
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :event_manager, :browser]

    resources "/events", EventController do
      resources "/activities", ActivityController, only: [:create, :new, :edit]
    end

    resources "/register", RegistrationController, only: [:index, :delete]
    resources "/activities", ActivityController, only: [:index, :delete, :create, :new, :edit, :update]
  end

  scope "/", GateGoatWeb do
    pipe_through [:protected, :browser]

    resources "/register", RegistrationController, only: [:edit, :update]
    resources "/users", UserController, only: [:edit, :update]

    get "/admin", AdminController, :index
    get "/lookup", LookupController, :lookup
    post "/lookup", LookupController, :lookup
  end

  scope "/", GateGoatWeb do
    pipe_through :browser # Use the default browser stack

    get "/", GateGoatController, :index
    get "/about", GateGoatController, :about
    get "/instructions", GateGoatController, :instructions
    get "/event/:id", GateGoatController, :register
    resources "/register", RegistrationController, only: [:show, :create, :new]
    resources "/activities", ActivityController, only: [:index, :show]

    resources "/events", EventController do
      resources "/activities", ActivityController, only: [:index]
    end

    get "/login", LoginController, :login
    post "/login", LoginController, :login
    post "/logout", LoginController, :logout
  end


  # Other scopes may use custom stacks.
  # scope "/api", GateGoatWeb do
  #   pipe_through :api
  # end
end

lib/gate_goat_web/controllers/lookup_controller.ex
defmodule GateGoatWeb.LookupController do
  use GateGoatWeb, :controller

  alias GateGoat.Registrations
  alias GateGoat.Events

  def lookup(conn, %{"action" => "disable", "feast" => %{"event" => event_id}}) do
    render_feast_change(conn, event_id, false, "disabled")
  end
  def lookup(conn, %{"action" => "enable", "feast" => %{"event" => event_id}}) do
    render_feast_change(conn, event_id, true, "enabled")
  end
  def lookup(conn, %{"search" => %{"confirmation_number" => registration_id}}) do
    registration = Registrations.get_registration(registration_id)

    cond do
      !Regex.match?(~r/^\d+$/, registration_id) || registration == nil ->
        conn
        |> put_flash(:error, "Please enter a valid confirmation number.")
        |> render_results()
      !verify_user_event(conn, registration) ->
        conn
        |> put_flash(:error, "This user registered for the wrong event.  Please have them re-register.")
        |> render_results()
      true ->
        render_results(conn, registration)
    end
  end
  def lookup(conn, %{"registration" => registration_id}) do
    registration = Registrations.get_registration(registration_id)
    Registrations.update_registration(registration, %{verified: true})

    conn
    |> put_flash(:info, "User verified.")
    |> render("lookup.html", verified: true, error: false)
  end
  def lookup(conn, _params) do
    render(conn, "lookup.html", error: false)
  end

  defp render_results(conn, nil), do: render_results(conn)
  defp render_results(conn, registration), do: render(conn, "display.html", registration: registration)
  defp render_results(conn), do: render(conn, "lookup.html", error: true)

  defp render_feast_change(conn, event_id, option, message) do
    event = Events.get_event!(String.to_integer(event_id))
    Events.update_event(event, %{feast_available: option})

    conn
    |> put_flash(:info, "Feast #{message} for #{event.event_name}.")
    |> render("lookup.html", verified: true, error: false)
  end

  defp verify_user_event(conn, registration) do
    user = GateGoat.AdminHelper.current_user(conn)

    if user.event == nil || registration == nil do
      false
    else
      registration.event.id == user.event.id
    end
  end
end

lib/gate_goat_web/views/lookup_view.ex
defmodule GateGoatWeb.LookupView do
  use GateGoatWeb, :view

  def payment(params) do
    GateGoatWeb.RegistrationView.payment(params)
  end

  def checks_payable(params) do
    GateGoatWeb.RegistrationView.checks_payable(params)
  end

  def get_events() do
    GateGoat.Events.list_current_events()
  end

  def feast_available(event) do
    if event.feast_available == true do
      "enabled"
    else
      "disabled"
    end
  end

  def feast_selected?(registration) do
    registration.registration_event_fee
    |> Enum.any?(fn(reg) -> reg.event_fee.fee.name == "Feast" && reg.selected end)
  end

  def feast_change(true, false), do: true
  def feast_change(_, _), do: false
end

lib/gate_goat_web/templates/lookup/display.html.eex
<%= unless GateGoat.Events.free_event?(GateGoat.Events.get_event!(@registration.event_id)) do %>
  <h3><strong>Payment:</strong> $<%= payment(@registration) %></h3>
<% end %>

<%= if @registration.verified do %>
  <div><strong>This user is already verified.</strong></div>
<% else %>
  <div>This user is not yet verified.</div>
<% end %>

<%= if feast_change(feast_selected?(@registration), @registration.event.feast_available) do %>
  <div><strong>This user has selected feast but feast is no longer available.  Please change the user's registration
  details so that feast is not selected and inform the user of the new amount due.</strong></div>
<% end %>

<hr>

<%= link "Paid", class: "button", to: Routes.lookup_path(@conn, :lookup, %{registration: @registration}) %>
  <%= link "Cancel", class: "button", to: Routes.lookup_path(@conn, :lookup) %>

<ul>
  <li>
    <strong>Event Name:</strong>
    <%= @registration.event.event_name %>
  </li>
  <li>
    <strong>Confirmation Number:</strong>
    <%= @registration.id %>
  </li>

  <li>
    <strong>Sca name:</strong>
    <%= @registration.sca_name %>
  </li>

  <li>
    <strong>Legal name:</strong>
    <%= @registration.legal_name %>
  </li>

  <li>
    <strong>Member?:</strong>
    <%= @registration.member_option %>
  </li>

  <%= if @registration.member_option do %>
    <li>
      <strong>Membership number:</strong>
      <%= @registration.membership_number %>
    </li>

    <li>
      <strong>Membership expiration date:</strong>
      <%= GateGoat.Helpers.elixir_to_human_date(@registration.membership_expiration_date) %>
    </li>
  <% end %>

  <li>
    <strong>Group name:</strong>
    <%= @registration.group_name %>
  </li>

  <%= for fee <- @registration.registration_event_fee do %>
    <li>
    <strong><%= fee.event_fee.fee.name %></strong>
    <%= fee.selected %>
  <% end %>

  <li>
    <strong>Waiver:</strong>
    <%= @registration.waiver %>
  </li>
</ul>

<%= link "Edit Registration", to: Routes.registration_path(@conn, :edit, @registration) %>

lib/gate_goat_web/templates/lookup/form.html.eex
<%= form_for @conn, Routes.lookup_path(@conn, :lookup), [as: :search], fn f -> %>

  <div class="form-group">
    <%= label f, :confirmation_number, class: "control-label" %>
    <%= text_input f, :confirmation_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "button" %>
  </div>
<% end %>

  <hr>

<%= form_for @conn, Routes.lookup_path(@conn, :lookup), [as: :feast], fn f -> %>
  Disable Feast Option - feast is currently <%= feast_available(GateGoat.AdminHelper.current_user(@conn).event) %>
  <div class="form-group">
    <label>
      Event: <%= select f, :event, Enum.map([GateGoat.AdminHelper.current_user(@conn).event], &{&1.event_name, &1.id}) %>
    </label>
    <%= submit "Disable", class: "button", name: "action", value: "disable" %>
    <%= submit "Enable", class: "button", name: "action", value: "enable" %>
  </div>
<% end %>

lib/gate_goat_web/templates/lookup/lookup.html.eex
<div class="logout">
  <%= form_for @conn, Routes.login_path(@conn, :login), [as: :logout], fn f -> %>
      <%= submit "Logout", class: "button" %>
  <% end %>
</div>


<%= render GateGoatWeb.LookupView, "form.html", conn: @conn, error: @error %>

<span><%= link "Back", to: Routes.admin_path(@conn, :index) %></span>